In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
%matplotlib inline 
import matplotlib.pyplot as plt
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix,accuracy_score

In [2]:
df=pd.read_csv('data-indian-liver-Patient.csv')
df.head()

Age  Gender    TB   DB  AAP  SGPT  SGOT   TP  ALB   AGR  Status
0   65  Female   0.7  0.1  187    16    18  6.8  3.3  0.90       1
1   62    Male  10.9  5.5  699    64   100  7.5  3.2  0.74       1
2   62    Male   7.3  4.1  490    60    68  7.0  3.3  0.89       1
3   58    Male   1.0  0.4  182    14    20  6.8  3.4  1.00       1
4   72    Male   3.9  2.0  195    27    59  7.3  2.4  0.40       1

In [3]:
df

Age  Gender    TB   DB  AAP  SGPT  SGOT   TP  ALB   AGR  Status
0     65  Female   0.7  0.1  187    16    18  6.8  3.3  0.90       1
1     62    Male  10.9  5.5  699    64   100  7.5  3.2  0.74       1
2     62    Male   7.3  4.1  490    60    68  7.0  3.3  0.89       1
3     58    Male   1.0  0.4  182    14    20  6.8  3.4  1.00       1
4     72    Male   3.9  2.0  195    27    59  7.3  2.4  0.40       1
..   ...     ...   ...  ...  ...   ...   ...  ...  ...   ...     ...
578   60    Male   0.5  0.1  500    20    34  5.9  1.6  0.37       2
579   40    Male   0.6  0.1   98    35    31  6.0  3.2  1.10       1
580   52    Male   0.8  0.2  245    48    49  6.4  3.2  1.00       1
581   31    Male   1.3  0.5  184    29    32  6.8  3.4  1.00       1
582   38    Male   1.0  0.3  216    21    24  7.3  4.4  1.50       2

[583 rows x 11 columns]

In [4]:
df.isnull().values.any()

True

In [5]:
null_columns=df.columns[df.isnull().any()]
print(df[df.isnull().any(axis=1)][null_columns].head())

     AGR
209  NaN
241  NaN
253  NaN
312  NaN


In [6]:

df.dropna(how='any', axis=0,inplace=True)

In [7]:
df

Age  Gender    TB   DB  AAP  SGPT  SGOT   TP  ALB   AGR  Status
0     65  Female   0.7  0.1  187    16    18  6.8  3.3  0.90       1
1     62    Male  10.9  5.5  699    64   100  7.5  3.2  0.74       1
2     62    Male   7.3  4.1  490    60    68  7.0  3.3  0.89       1
3     58    Male   1.0  0.4  182    14    20  6.8  3.4  1.00       1
4     72    Male   3.9  2.0  195    27    59  7.3  2.4  0.40       1
..   ...     ...   ...  ...  ...   ...   ...  ...  ...   ...     ...
578   60    Male   0.5  0.1  500    20    34  5.9  1.6  0.37       2
579   40    Male   0.6  0.1   98    35    31  6.0  3.2  1.10       1
580   52    Male   0.8  0.2  245    48    49  6.4  3.2  1.00       1
581   31    Male   1.3  0.5  184    29    32  6.8  3.4  1.00       1
582   38    Male   1.0  0.3  216    21    24  7.3  4.4  1.50       2

[579 rows x 11 columns]

In [9]:
df['Gender'].value_counts()

Male      439
Female    140
Name: Gender, dtype: int64

In [11]:
df['Status'].value_counts()

1    414
2    165
Name: Status, dtype: int64

In [10]:
d = {'Female':1 , 'Male': 0}
df['Gender'] = df['Gender'].map(d)

In [12]:
X = df[['Age', 'Gender', 'TB', 'DB', 'AAP', 'SGPT', 'SGOT', 'TP', 'ALB', 'AGR']]
y = df['Status']

In [13]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (463, 10) (463,)
Test set: (116, 10) (116,)


In [14]:
from sklearn import svm
clf = svm.SVC(kernel='rbf')
clf.fit(X_train,y_train) 

SVC()

In [15]:
pred=clf.predict(X_test)
print(classification_report(y_test, pred))
print('\nAccuracy: {0:.4f}'.format(accuracy_score(y_test, pred)))
print(confusion_matrix(y_test,pred))

              precision    recall  f1-score   support

           1       0.69      1.00      0.82        80
           2       0.00      0.00      0.00        36

    accuracy                           0.69       116
   macro avg       0.34      0.50      0.41       116
weighted avg       0.48      0.69      0.56       116


Accuracy: 0.6897
[[80  0]
 [36  0]]


C:\Users\Thoufiq\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Thoufiq\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Thoufiq\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [16]:
from sklearn import svm
clfL = svm.SVC(kernel='linear')
clfL.fit(X_train, y_train) 

SVC(kernel='linear')

In [17]:
pred1=clfL.predict(X_test)
print(classification_report(y_test, pred1))
print('\nAccuracy: {0:.4f}'.format(accuracy_score(y_test, pred1)))
print(confusion_matrix(y_test,pred1))

              precision    recall  f1-score   support

           1       0.69      1.00      0.82        80
           2       0.00      0.00      0.00        36

    accuracy                           0.69       116
   macro avg       0.34      0.50      0.41       116
weighted avg       0.48      0.69      0.56       116


Accuracy: 0.6897
[[80  0]
 [36  0]]


C:\Users\Thoufiq\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Thoufiq\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Thoufiq\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [18]:
clfP = svm.SVC(C=2.0, kernel='poly', degree=3)
clfP.fit(X_train, y_train) 

SVC(C=2.0, kernel='poly')

In [19]:
pred2=clfP.predict(X_test)
print(classification_report(y_test, pred2))
print('\nAccuracy: {0:.4f}'.format(accuracy_score(y_test, pred2)))
print(confusion_matrix(y_test,pred2))

              precision    recall  f1-score   support

           1       0.69      1.00      0.82        80
           2       0.00      0.00      0.00        36

    accuracy                           0.69       116
   macro avg       0.34      0.50      0.41       116
weighted avg       0.48      0.69      0.56       116


Accuracy: 0.6897
[[80  0]
 [36  0]]


C:\Users\Thoufiq\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Thoufiq\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Thoufiq\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
