In [1]:
import pandas as pd
# Loading dataset

iris_df = pd.read_csv('Iris.csv')

In [2]:
iris_df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
print (iris_df.isnull().sum())
print (iris_df.info())

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None


In [4]:
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()
iris_df['species'] = LE.fit_transform(iris_df['species'])
iris_df.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [6]:
X = iris_df.drop('species', axis = 1)
y = iris_df['species']

In [7]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix

In [8]:
test_size = 0.30 # taking 70:30 training and test set
seed = 7  # Random numbmer seeding for reapeatability of the code
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=seed)


In [9]:
KNN = KNeighborsClassifier(n_neighbors=11)

In [10]:
KNN.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=11)

In [11]:
y_pred = KNN.predict(X_test)

In [12]:
from sklearn.metrics import accuracy_score

In [13]:
accuracy_score(y_pred,y_test)

0.9111111111111111

In [14]:
metrics.confusion_matrix(y_train, KNN.predict(X_train))

array([[38,  0,  0],
       [ 0, 33,  1],
       [ 0,  0, 33]], dtype=int64)

In [15]:
metrics.confusion_matrix(y_test, y_pred)

array([[12,  0,  0],
       [ 0, 14,  2],
       [ 0,  2, 15]], dtype=int64)

In [16]:
print(("Test accuracy: ", KNN.score(X_test, y_test)))

print(("Train accuracy: ",KNN.score(X_train, y_train)))

('Test accuracy: ', 0.9111111111111111)
('Train accuracy: ', 0.9904761904761905)


In [17]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[12  0  0]
 [ 0 14  2]
 [ 0  2 15]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.88      0.88      0.88        16
           2       0.88      0.88      0.88        17

    accuracy                           0.91        45
   macro avg       0.92      0.92      0.92        45
weighted avg       0.91      0.91      0.91        45



### Cross Validation to find optimal K

In [18]:
import numpy as np
from sklearn.model_selection import cross_val_score
print(X_train.shape[0])
print (int(np.sqrt(X_train.shape[0])))
maxK = int(np.sqrt(X_train.shape[0]))
print(maxK)

105
10
10


In [19]:
# creating odd list of K for KNN
myList = list(range(1,15))
# subsetting just the odd ones
neighbors = list(filter(lambda x: x % 2 != 0, myList))

In [ ]:
# empty list that will hold cv scores
cv_scores = []
# perform 10-fold cross validation
for k in neighbors:
    knn = KNeighborsClassifier(n_neighbors=k)
    scores = cross_val_score(knn, X_train, y_train, cv=10, scoring='accuracy')
    cv_scores.append(scores.mean())

In [ ]:
# changing to misclassification error
misError = [1 - x for x in cv_scores]

In [ ]:
# determining best k
optimal_k = neighbors[misError.index(min(misError))]
print("The optimal number of neighbors is %d" % optimal_k)